# Generated by Django 4.0.4 on 2022-05-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('order_count', models.IntegerField()),
                ('purchase_percent', models.FloatField()),
                ('card_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('cells_count', models.IntegerField()),
                ('max_goods', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PickPointCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer')),
                ('pick_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pickpoint')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=20, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.good')),
                ('pick_point_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pickpointcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('0', 'Created'), ('1', 'Formed'), ('2', 'Sent'), ('3', 'Arrived'), ('4', 'Received'), ('5', 'Canceled'), ('6', 'Sent Back')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orderedgood')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_pick_points',
            field=models.ManyToManyField(to='main_app.pickpoint'),
        ),
    ]
