# Generated by Django 4.0.6 on 2022-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_card_balance_alter_customer_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='SDS'),
        ),
    ]
