# Generated by Django 4.0.4 on 2022-06-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_customer_fio_alter_customer_card_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='saved_pick_points',
            field=models.ManyToManyField(to='main_app.pickpoint'),
        ),
    ]
