# Generated by Django 4.0.6 on 2022-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_balance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент выкупа'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='saved_pick_points',
            field=models.ManyToManyField(blank=True, to='main_app.pickpoint', verbose_name='Сохраненные пункты выдачи'),
        ),
    ]
