# Generated by Django 4.0.6 on 2022-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_seller_description_seller_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
