# Generated by Django 4.0.6 on 2022-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_customer_card_balance_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_percent',
            field=models.FloatField(default=1, verbose_name='Процент выкупа'),
        ),
    ]
