# Generated by Django 4.0.6 on 2022-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_customer_order_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to='sellers', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(null=True, upload_to='goods', verbose_name='Изображение'),
        ),
    ]
