# Generated by Django 4.0.6 on 2022-07-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_seller_image_alter_good_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='pickpoint',
            options={'verbose_name': 'Пункт выдачи', 'verbose_name_plural': 'Пункты выдачи'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddField(
            model_name='customer',
            name='basket',
            field=models.ManyToManyField(blank=True, to='main_app.good', verbose_name='Корзина товаров'),
        ),
    ]
