# Generated by Django 4.0.4 on 2022-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_customer_active_remove_customer_session_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
