# Generated by Django 4.0.6 on 2022-07-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_customer_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(max_length=30, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
