# Generated by Django 4.0.6 on 2022-07-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_cart_promo_code_alter_cart_count_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
