# Generated by Django 4.0.6 on 2022-07-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_cart_count_alter_cart_promo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('value', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('promo_code_type', models.CharField(choices=[('DISCOUNT_5', 'Скидка 5%'), ('DISCOUNT_10', 'Скидка 10%'), ('DISCOUNT_20', 'Скидка 20%')], max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
