# Generated by Django 4.0.6 on 2022-07-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_customer_card_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название промокода'),
        ),
        migrations.AlterField(
            model_name='cartgood',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_goods', to='main_app.cart', verbose_name='Корзина'),
        ),
    ]
