# Generated by Django 4.0.6 on 2022-07-21 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_cartgood_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(max_length=100, verbose_name='Адрес отправителя')),
                ('recipient_address', models.CharField(max_length=100, verbose_name='Адрес получателя')),
                ('driver_payment', models.PositiveSmallIntegerField(verbose_name='Оплата')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=100, verbose_name='Паспортные данные')),
                ('license', models.CharField(max_length=50, verbose_name='Водительские права')),
                ('payroll_card', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер зарплатной карты')),
                ('fuel_card', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер топливной карты')),
                ('hourly_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Почасовая ставка')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('license_plate', models.CharField(max_length=8, verbose_name='Регистрационный номер')),
                ('category', models.PositiveSmallIntegerField(choices=[('0', 'B'), ('1', 'C'), ('2', 'D')], verbose_name='Категория')),
                ('registration', models.ImageField(upload_to='vehicle/registrations', verbose_name='Свидетельство о регистрации')),
                ('insurance', models.ImageField(blank=True, null=True, upload_to='vehicles/insurances', verbose_name='ОСАГО И КАСКО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos', verbose_name='Фотография')),
                ('ready_for_carriage', models.BooleanField(verbose_name='Готова к перевозкам')),
                ('in_work', models.BooleanField(verbose_name='В работе')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderedgood',
            name='pick_point_customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='orderedgood',
            name='bar_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('pick_point_cell', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ячейка')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pick_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.pickpoint')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.IntegerField(choices=[('0', 'Created'), ('1', 'Formed'), ('2', 'Transit'), ('3', 'Completed'), ('4', 'Canceled')], verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='main_app.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='ordered_goods',
            field=models.ManyToManyField(to='main_app.orderedgood'),
        ),
        migrations.AddField(
            model_name='orderedgood',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order'),
        ),
    ]
