# Generated by Django 4.0.6 on 2022-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_order_options_alter_orderedgood_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.SmallIntegerField(choices=[('0', 'B'), ('1', 'C'), ('2', 'D')], verbose_name='Категория'),
        ),
    ]
