# Generated by Django 4.0.6 on 2022-07-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_vehicle_options_alter_vehicle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration',
        ),
    ]
