# Generated by Django 4.0.6 on 2022-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_vehicle_insurance_remove_vehicle_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес доставки'),
        ),
    ]
