# Generated by Django 4.0.6 on 2022-07-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_order_delivery_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedGoodStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.IntegerField(choices=[('Создан', 'Created'), ('Сформирован', 'Formed'), ('Отправлен', 'Sent'), ('Прибыл в пункт выдачи', 'Arrived'), ('Получен клиентом', 'Received'), ('Отменён', 'Canceled')], max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('ordered_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='main_app.orderedgood')),
            ],
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status_type',
            field=models.CharField(choices=[('Создана', 'Created'), ('Сформирована', 'Formed'), ('В пути', 'Transit'), ('Завершена', 'Completed'), ('Отменена', 'Canceled')], max_length=30, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='GoodsStatus',
        ),
    ]
