# Generated by Django 4.0.6 on 2022-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_orderedgoodstatus_alter_deliverystatus_status_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedgoodstatus',
            options={'verbose_name': 'Статус товара', 'verbose_name_plural': 'Статусы товара'},
        ),
        migrations.AlterField(
            model_name='orderedgoodstatus',
            name='status_type',
            field=models.CharField(choices=[('Создан', 'Created'), ('Сформирован', 'Formed'), ('Отправлен', 'Sent'), ('Прибыл в пункт выдачи', 'Arrived'), ('Получен клиентом', 'Received'), ('Отменён', 'Canceled')], max_length=30, verbose_name='Статус'),
        ),
    ]
