# Generated by Django 4.0.6 on 2022-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_type',
            field=models.CharField(choices=[('Создан', 'Created'), ('В работе', 'In Work'), ('Завершен', 'Completed')], default='Создан', max_length=30, verbose_name='Статус'),
        ),
    ]
