# Generated by Django 4.0.6 on 2022-07-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_order_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickpoint',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pickpoint',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
