# Generated by Django 4.0.6 on 2022-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_goodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcategory',
            name='landing',
            field=models.BooleanField(default=False),
        ),
    ]
