# Generated by Django 4.0.6 on 2022-08-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_goodcategory_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='goodcategory',
            name='query',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='goodcategory',
            name='shard',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goodcategory',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
