# Generated by Django 4.0.6 on 2022-08-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_goodcategory_name_alter_goodcategory_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='query',
            field=models.CharField(max_length=1000),
        ),
    ]
