# Generated by Django 4.0.6 on 2022-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_alter_goodcategory_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcategory',
            name='landing',
        ),
    ]
