# Generated by Django 4.0.6 on 2022-08-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_pickpoint_city_alter_pickpoint_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpoint',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
    ]
