# Generated by Django 4.0.6 on 2022-08-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_alter_pickpoint_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpoint',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
